In [1]:
import yfinance as yf
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime
import talib

In [2]:
stock_codes = ["ABEV3", "ASAI3", "AXIA3"]
stock_codes_with_sa = [code + '.SA' for code in stock_codes]
print(stock_codes_with_sa)

['ABEV3.SA', 'ASAI3.SA', 'AXIA3.SA']

In [17]:
yf.download(stock_codes_with_sa, start='2025-01-01', end='2025-12-12')

[*********************100%***********************]  3 of 3 completed

Price           Close                            High                       \
Ticker       ABEV3.SA  ASAI3.SA   AXIA3.SA   ABEV3.SA  ASAI3.SA   AXIA3.SA
Date
2025-01-02  10.202848  5.281979  31.018431  10.457920  5.437047  31.365108
2025-01-03   9.965367  5.252904  30.607895  10.158870  5.340129  31.082295
2025-01-06   9.930185  5.514580  31.000183  10.114892  5.621189  31.155277
2025-01-07  10.150074  5.714286  31.173521  10.185256  5.793104  31.383355
2025-01-08  10.044528  5.556650  31.118782  10.141279  5.645320  31.337734
...               ...       ...        ...        ...       ...        ...
2025-12-05  12.192096  8.456662  63.099998  12.640005  9.364495  67.839996
2025-12-08  12.201054  8.081687  63.820000  12.326469  8.644149  64.699997
2025-12-09  12.218970  8.032350  64.790001  12.308552  8.190233  65.290001
2025-12-10  12.183138  7.904068  63.560001  12.227928  8.081687  65.080002
2025-12-11  12.344385  7.765920  62.840000  12.398135  7.973142  63.650002

Price             Low                            Open                       \
Ticker       ABEV3.SA  ASAI3.SA   AXIA3.SA   ABEV3.SA  ASAI3.SA   AXIA3.SA
Date
2025-01-02  10.106097  5.194754  30.772107  10.308395  5.427355  31.155278
2025-01-03   9.912594  5.165678  30.434558  10.106096  5.301362  30.899833
2025-01-06   9.859821  5.417663  30.626137   9.991754  5.417663  30.963690
2025-01-07   9.912594  5.566503  31.009309   9.938981  5.704433  31.173521
2025-01-08   9.921390  5.359606  30.607889  10.097301  5.635467  30.945442
...               ...       ...        ...        ...       ...        ...
2025-12-05  12.174180  8.456662  62.830002  12.514591  9.364495  66.709999
2025-12-08  12.174179  8.042216  63.419998  12.263761  8.584942  64.400002
2025-12-09  12.057723  7.637639  62.680000  12.102514  7.992879  63.490002
2025-12-10  11.771061  7.805391  63.470001  11.878559  8.002745  65.000000
2025-12-11  12.021891  7.756052  61.770000  12.120430  7.874465  63.330002

Price         Volume
Ticker      ABEV3.SA  ASAI3.SA  AXIA3.SA
Date
2025-01-02  33417900  15340600  10854400
2025-01-03  41365900  13594200  14388900
2025-01-06  50881500  13729000   8139400
2025-01-07  34905200  22063000   4703200
2025-01-08  39248800  27185400  10582100
...              ...       ...       ...
2025-12-05  61741400  35244300  18274900
2025-12-08  19119600  19594800   9104600
2025-12-09  38541700  17817900   8614900
2025-12-10  91743100  14659000   7714400
2025-12-11  22635200  16401600  13767500

[239 rows x 15 columns]

In [4]:
def obter_cotacoes(data_referencia, codigos_acoes):
    lista_dfs = []

    for cdgo in codigos_acoes:
        # Baixar dados
        df = yf.download(cdgo, start=data_referencia, progress=False)
        
        # Correção para MultiIndex do yfinance (se necessário)
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.droplevel(1)
            
        df = df.reset_index()
        df['CD_ACAO'] = cdgo
        
        # Selecionar colunas e adicionar à lista
        if 'Close' in df.columns and 'Volume' in df.columns:
            df = df[['Date', 'CD_ACAO', 'Close', 'Volume']]
            lista_dfs.append(df)
            
    return lista_dfs
data_referencia = '2025-01-01'

In [5]:
ne = obter_cotacoes(data_referencia, stock_codes_with_sa)
ne

[Price       Date   CD_ACAO      Close    Volume
 0     2025-01-02  ABEV3.SA  10.202848  33417900
 1     2025-01-03  ABEV3.SA   9.965368  41365900
 2     2025-01-06  ABEV3.SA   9.930185  50881500
 3     2025-01-07  ABEV3.SA  10.150074  34905200
 4     2025-01-08  ABEV3.SA  10.044528  39248800
 ..           ...       ...        ...       ...
 280   2026-02-13  ABEV3.SA  16.350000  23238400
 281   2026-02-18  ABEV3.SA  16.129999  29705300
 282   2026-02-19  ABEV3.SA  16.170000  23244500
 283   2026-02-20  ABEV3.SA  16.030001  33875800
 284   2026-02-23  ABEV3.SA  16.190001  29917200

 [285 rows x 4 columns],
 Price       Date   CD_ACAO     Close    Volume
 0     2025-01-02  ASAI3.SA  5.281979  15340600
 1     2025-01-03  ASAI3.SA  5.252904  13594200
 2     2025-01-06  ASAI3.SA  5.514580  13729000
 3     2025-01-07  ASAI3.SA  5.714286  22063000
 4     2025-01-08  ASAI3.SA  5.556650  27185400
 ..           ...       ...       ...       ...
 280   2026-02-13  ASAI3.SA  9.900000  24336600
 281   2026-02-18  ASAI3.SA  9.640000  15515700
 282   2026-02-19  ASAI3.SA  9.460000  13227400
 283   2026-02-20  ASAI3.SA  9.500000  14268100
 284   2026-02-23  ASAI3.SA  9.270000  22247600

 [285 rows x 4 columns],
 Price       Date   CD_ACAO      Close    Volume
 0     2025-01-02  AXIA3.SA  31.018433  10854400
 1     2025-01-03  AXIA3.SA  30.607893  14388900
 2     2025-01-06  AXIA3.SA  31.000187   8139400
 3     2025-01-07  AXIA3.SA  31.173519   4703200
 4     2025-01-08  AXIA3.SA  31.118786  10582100
 ..           ...       ...        ...       ...
 280   2026-02-13  AXIA3.SA  58.430000   6783100
 281   2026-02-18  AXIA3.SA  58.580002   7373000
 282   2026-02-19  AXIA3.SA  61.180000  13968500
 283   2026-02-20  AXIA3.SA  61.200001  16408300
 284   2026-02-23  AXIA3.SA  60.529999   6964000

 [285 rows x 4 columns]]

In [13]:
talib.BBANDS(df['Close'])

(0            NaN
 1            NaN
 2            NaN
 3            NaN
 4      31.380741
          ...
 280    59.625988
 281    59.629622
 282    61.333370
 283    62.178558
 284    62.448681
 Length: 285, dtype: float64,
 0            NaN
 1            NaN
 2            NaN
 3            NaN
 4      30.983764
          ...
 280    58.870000
 281    58.860000
 282    59.326000
 283    59.656001
 284    59.984000
 Length: 285, dtype: float64,
 0            NaN
 1            NaN
 2            NaN
 3            NaN
 4      30.586786
          ...
 280    58.114011
 281    58.090378
 282    57.318630
 283    57.133443
 284    57.519319
 Length: 285, dtype: float64)

In [14]:
for df in ne:
    df['RSI'] = talib.RSI(df['Close'].values, timeperiod=14)
    macd, signal, hist = talib.MACD(df['Close'].values)
    df['MACD'] = macd
    df['MACD_Signal'] = signal
    df['MACD_Hist'] = hist
    ##df['OBV'] = talib.OBV(df['Close'],df['Volume']) 
    upper, middle, lower = talib.BBANDS(df['Close'].values, timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)
    df['BB_Upper'] = upper
    df['BB_Middle'] = middle
    df['BB_Lower'] = lower
    
    

ne[1]

Price,Date,CD_ACAO,Close,Volume,RSI,MACD,MACD_Signal,MACD_Hist,OBV,BB_Upper,BB_Middle,BB_Lower
0,2025-01-02,ASAI3.SA,5.281979,15340600,NaN,NaN,NaN,NaN,15340600.0,NaN,NaN,NaN
1,2025-01-03,ASAI3.SA,5.252904,13594200,NaN,NaN,NaN,NaN,1746400.0,NaN,NaN,NaN
2,2025-01-06,ASAI3.SA,5.514580,13729000,NaN,NaN,NaN,NaN,15475400.0,NaN,NaN,NaN
3,2025-01-07,ASAI3.SA,5.714286,22063000,NaN,NaN,NaN,NaN,37538400.0,NaN,NaN,NaN
4,2025-01-08,ASAI3.SA,5.556650,27185400,NaN,NaN,NaN,NaN,10353000.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
280,2026-02-13,ASAI3.SA,9.900000,24336600,76.513529,0.438215,0.311423,0.126791,11813100.0,9.845128,8.5950,7.344872
281,2026-02-18,ASAI3.SA,9.640000,15515700,69.417897,0.456232,0.340385,0.115847,-3702600.0,9.917372,8.7045,7.491628
282,2026-02-19,ASAI3.SA,9.460000,13227400,64.928636,0.450790,0.362466,0.088324,-16930000.0,9.919802,8.8035,7.687198
283,2026-02-20,ASAI3.SA,9.500000,14268100,65.463147,0.444580,0.378889,0.065691,-2661900.0,9.930129,8.8925,7.854870
284,2026-02-23,ASAI3.SA,9.270000,22247600,59.817843,0.416301,0.386371,0.029929,-24909500.0,9.920228,8.9560,7.991772