In [1]:
import yfinance as yf
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime
import talib

In [2]:
stock_codes = ["ABEV3", "ASAI3", "AXIA3"]
stock_codes_with_sa = [code + '.SA' for code in stock_codes]
print(stock_codes_with_sa)

['ABEV3.SA', 'ASAI3.SA', 'AXIA3.SA']

In [3]:
yf.download(stock_codes_with_sa, start='2024-01-01', end='2025-01-01')

[*********************100%***********************]  3 of 3 completed

Price           Close                             High                        \
Ticker       ABEV3.SA   ASAI3.SA   AXIA3.SA   ABEV3.SA   ASAI3.SA   AXIA3.SA
Date
2024-01-02  11.428789  12.618601  36.742973  11.445461  13.035344  37.297549
2024-01-03  11.337093  12.541065  36.698952  11.462135  12.715516  37.103884
2024-01-04  11.378773  12.802742  36.382053  11.403782  12.919042  36.839797
2024-01-05  11.337093  13.161335  36.320427  11.412118  13.616845  36.681342
2024-01-08  11.428789  13.733146  36.144375  11.462133  13.733146  36.399654
...               ...        ...        ...        ...        ...        ...
2024-12-20  10.756968   5.592113  31.348095  10.818538   5.659956  31.623938
2024-12-23  10.748173   5.611497  30.920990  10.853719   5.718106  31.303610
2024-12-26  10.677809   5.727798  31.107849  10.765764   5.747181  31.410386
2024-12-27  10.616239   5.553347  31.143438  10.721785   5.776256  31.463771
2024-12-30  10.325985   5.456430  31.137032  10.695398   5.640572  31.237386

Price             Low                             Open                        \
Ticker       ABEV3.SA   ASAI3.SA   AXIA3.SA   ABEV3.SA   ASAI3.SA   AXIA3.SA
Date
2024-01-02  11.328756  12.502300  36.540506  11.437125  13.035344  36.989451
2024-01-03  11.312084  12.318156  36.575713  11.395446  12.628291  36.795783
2024-01-04  11.270404  12.444149  36.047545  11.337093  12.502299  36.751770
2024-01-05  11.278740  12.744591  36.100356  11.353765  12.802742  36.267612
2024-01-08  11.320420  13.093493  35.827473  11.345428  13.151643  36.294021
...               ...        ...        ...        ...        ...        ...
2024-12-20  10.563467   5.165678  31.063355  10.625035   5.223829  31.534955
2024-12-23  10.545874   5.475813  30.814213  10.651421   5.514580  31.232423
2024-12-26  10.545875   5.504889  30.876499  10.712991   5.601806  30.965479
2024-12-27  10.528284   5.437046  31.072252  10.695399   5.766564  31.241318
2024-12-30  10.325985   5.330438  30.653507  10.607443   5.582422  30.936323

Price         Volume
Ticker      ABEV3.SA  ASAI3.SA  AXIA3.SA
Date
2024-01-02  11690200   7348700   3568400
2024-01-03  17612200   6830500   3762800
2024-01-04  19996000   8604100   3017000
2024-01-05  18293900  12696400   3085000
2024-01-08  11014600  17538900   3643100
...              ...       ...       ...
2024-12-20  86074600  45865200  16048900
2024-12-23  40181700  24589900   6615800
2024-12-26  21166800  25976300   5387300
2024-12-27  37624000  30175900   7961400
2024-12-30  38907400  17975800   6821300

[251 rows x 15 columns]

In [4]:
def obter_cotacoes(data_referencia, codigos_acoes):
    lista_dfs = []

    for cdgo in codigos_acoes:
        # Baixar dados
        df = yf.download(cdgo, start=data_referencia, progress=False)
        
        # Correção para MultiIndex do yfinance (se necessário)
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.droplevel(1)
            
        df = df.reset_index()
        df['CD_ACAO'] = cdgo
        
        # Selecionar colunas e adicionar à lista
        if 'Close' in df.columns and 'Volume' in df.columns:
            df = df[['Date', 'CD_ACAO', 'Close', 'Volume']]
            lista_dfs.append(df)
            
    return lista_dfs
data_referencia = '2025-01-01'

In [5]:
ne = obter_cotacoes(data_referencia, stock_codes_with_sa)
ne

[Price       Date   CD_ACAO      Close    Volume
 0     2025-01-02  ABEV3.SA  10.202848  33417900
 1     2025-01-03  ABEV3.SA   9.965368  41365900
 2     2025-01-06  ABEV3.SA   9.930185  50881500
 3     2025-01-07  ABEV3.SA  10.150074  34905200
 4     2025-01-08  ABEV3.SA  10.044528  39248800
 ..           ...       ...        ...       ...
 276   2026-02-09  ABEV3.SA  15.390000  22980900
 277   2026-02-10  ABEV3.SA  15.660000  35103300
 278   2026-02-11  ABEV3.SA  15.770000  26720300
 279   2026-02-12  ABEV3.SA  16.520000  55037900
 280   2026-02-13  ABEV3.SA  16.350000  23238400

 [281 rows x 4 columns],
 Price       Date   CD_ACAO     Close    Volume
 0     2025-01-02  ASAI3.SA  5.281979  15340600
 1     2025-01-03  ASAI3.SA  5.252904  13594200
 2     2025-01-06  ASAI3.SA  5.514580  13729000
 3     2025-01-07  ASAI3.SA  5.714285  22063000
 4     2025-01-08  ASAI3.SA  5.556650  27185400
 ..           ...       ...       ...       ...
 276   2026-02-09  ASAI3.SA  8.780000  23011400
 277   2026-02-10  ASAI3.SA  8.900000   9177800
 278   2026-02-11  ASAI3.SA  9.230000  15575900
 279   2026-02-12  ASAI3.SA  9.700000  38039200
 280   2026-02-13  ASAI3.SA  9.900000  24336600

 [281 rows x 4 columns],
 Price       Date   CD_ACAO      Close    Volume
 0     2025-01-02  AXIA3.SA  31.018433  10854400
 1     2025-01-03  AXIA3.SA  30.607889  14388900
 2     2025-01-06  AXIA3.SA  31.000185   8139400
 3     2025-01-07  AXIA3.SA  31.173521   4703200
 4     2025-01-08  AXIA3.SA  31.118784  10582100
 ..           ...       ...        ...       ...
 276   2026-02-09  AXIA3.SA  58.630001   7826300
 277   2026-02-10  AXIA3.SA  58.849998  10261000
 278   2026-02-11  AXIA3.SA  59.549999   7221100
 279   2026-02-12  AXIA3.SA  58.889999   9280100
 280   2026-02-13  AXIA3.SA  58.430000   6783100

 [281 rows x 4 columns]]

In [ ]:
for df in ne:
    df['RSI'] = talib.RSI(df['Close'].values, timeperiod=14)
    macd, signal, hist = talib.MACD(df['Close'].values)
    df['MACD'] = macd
    df['MACD_Signal'] = signal
    df['MACD_Hist'] = hist
    

ne[1]

Price,Date,CD_ACAO,Close,Volume,RSI,MACD,MACD_Signal,MACD_Hist
0,2025-01-02,ASAI3.SA,5.281979,15340600,NaN,NaN,NaN,NaN
1,2025-01-03,ASAI3.SA,5.252904,13594200,NaN,NaN,NaN,NaN
2,2025-01-06,ASAI3.SA,5.514580,13729000,NaN,NaN,NaN,NaN
3,2025-01-07,ASAI3.SA,5.714285,22063000,NaN,NaN,NaN,NaN
4,2025-01-08,ASAI3.SA,5.556650,27185400,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
276,2026-02-09,ASAI3.SA,8.780000,23011400,62.643853,0.289236,0.220900,0.068336
277,2026-02-10,ASAI3.SA,8.900000,9177800,64.617728,0.296929,0.236106,0.060823
278,2026-02-11,ASAI3.SA,9.230000,15575900,69.405358,0.325897,0.254064,0.071833
279,2026-02-12,ASAI3.SA,9.700000,38039200,74.663681,0.382371,0.279725,0.102646
280,2026-02-13,ASAI3.SA,9.900000,24336600,76.513529,0.438215,0.311423,0.126791