In [1]:
import yfinance as yf
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime
import talib

In [2]:
stock_codes = ["ABEV3", "ASAI3", "AXIA3"]
stock_codes_with_sa = [code + '.SA' for code in stock_codes]
print(stock_codes_with_sa)

['ABEV3.SA', 'ASAI3.SA', 'AXIA3.SA']

In [3]:
yf.download(stock_codes_with_sa, start='2024-01-01', end='2025-01-01')

[*********************100%***********************]  3 of 3 completed

Price           Close                             High                        \
Ticker       ABEV3.SA   ASAI3.SA   AXIA3.SA   ABEV3.SA   ASAI3.SA   AXIA3.SA
Date
2024-01-02  11.428789  12.618600  36.742970  11.445461  13.035343  37.297545
2024-01-03  11.337092  12.541066  36.698948  11.462134  12.715517  37.103880
2024-01-04  11.378773  12.802742  36.382050  11.403782  12.919042  36.839793
2024-01-05  11.337092  13.161336  36.320431  11.412117  13.616846  36.681346
2024-01-08  11.428789  13.733146  36.144375  11.462133  13.733146  36.399654
...               ...        ...        ...        ...        ...        ...
2024-12-20  10.756968   5.592113  31.348095  10.818537   5.659956  31.623938
2024-12-23  10.748173   5.611497  30.920986  10.853719   5.718106  31.303606
2024-12-26  10.677809   5.727798  31.107849  10.765764   5.747181  31.410386
2024-12-27  10.616239   5.553347  31.143442  10.721785   5.776256  31.463775
2024-12-30  10.325985   5.456430  31.137032  10.695398   5.640572  31.237386

Price             Low                             Open                        \
Ticker       ABEV3.SA   ASAI3.SA   AXIA3.SA   ABEV3.SA   ASAI3.SA   AXIA3.SA
Date
2024-01-02  11.328756  12.502299  36.540502  11.437125  13.035343  36.989447
2024-01-03  11.312084  12.318157  36.575709  11.395445  12.628292  36.795779
2024-01-04  11.270404  12.444149  36.047542  11.337093  12.502299  36.751766
2024-01-05  11.278739  12.744592  36.100360  11.353764  12.802743  36.267616
2024-01-08  11.320420  13.093493  35.827473  11.345428  13.151643  36.294021
...               ...        ...        ...        ...        ...        ...
2024-12-20  10.563466   5.165678  31.063355  10.625035   5.223829  31.534955
2024-12-23  10.545874   5.475813  30.814210  10.651421   5.514580  31.232419
2024-12-26  10.545875   5.504888  30.876499  10.712991   5.601806  30.965479
2024-12-27  10.528284   5.437046  31.072256  10.695399   5.766564  31.241322
2024-12-30  10.325985   5.330438  30.653507  10.607443   5.582422  30.936323

Price         Volume
Ticker      ABEV3.SA  ASAI3.SA  AXIA3.SA
Date
2024-01-02  11690200   7348700   3568400
2024-01-03  17612200   6830500   3762800
2024-01-04  19996000   8604100   3017000
2024-01-05  18293900  12696400   3085000
2024-01-08  11014600  17538900   3643100
...              ...       ...       ...
2024-12-20  86074600  45865200  16048900
2024-12-23  40181700  24589900   6615800
2024-12-26  21166800  25976300   5387300
2024-12-27  37624000  30175900   7961400
2024-12-30  38907400  17975800   6821300

[251 rows x 15 columns]

In [4]:
def obter_cotacoes(data_referencia, codigos_acoes):
    lista_dfs = []

    for cdgo in codigos_acoes:
        # Baixar dados
        df = yf.download(cdgo, start=data_referencia, progress=False)
        
        # Correção para MultiIndex do yfinance (se necessário)
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.droplevel(1)
            
        df = df.reset_index()
        df['CD_ACAO'] = cdgo
        
        # Selecionar colunas e adicionar à lista
        if 'Close' in df.columns and 'Volume' in df.columns:
            df = df[['Date', 'CD_ACAO', 'Close', 'Volume']]
            lista_dfs.append(df)
            
    return lista_dfs
data_referencia = '2025-01-01'

In [5]:
ne = obter_cotacoes(data_referencia, stock_codes_with_sa)
ne

[Price       Date   CD_ACAO      Close    Volume
 0     2025-01-02  ABEV3.SA  10.202848  33417900
 1     2025-01-03  ABEV3.SA   9.965368  41365900
 2     2025-01-06  ABEV3.SA   9.930185  50881500
 3     2025-01-07  ABEV3.SA  10.150074  34905200
 4     2025-01-08  ABEV3.SA  10.044528  39248800
 ..           ...       ...        ...       ...
 280   2026-02-13  ABEV3.SA  16.350000  23238400
 281   2026-02-18  ABEV3.SA  16.129999  29705300
 282   2026-02-19  ABEV3.SA  16.170000  23244500
 283   2026-02-20  ABEV3.SA  16.030001  33875800
 284   2026-02-23  ABEV3.SA  16.190001  29917200

 [285 rows x 4 columns],
 Price       Date   CD_ACAO     Close    Volume
 0     2025-01-02  ASAI3.SA  5.281979  15340600
 1     2025-01-03  ASAI3.SA  5.252904  13594200
 2     2025-01-06  ASAI3.SA  5.514580  13729000
 3     2025-01-07  ASAI3.SA  5.714286  22063000
 4     2025-01-08  ASAI3.SA  5.556650  27185400
 ..           ...       ...       ...       ...
 280   2026-02-13  ASAI3.SA  9.900000  24336600
 281   2026-02-18  ASAI3.SA  9.640000  15515700
 282   2026-02-19  ASAI3.SA  9.460000  13227400
 283   2026-02-20  ASAI3.SA  9.500000  14268100
 284   2026-02-23  ASAI3.SA  9.270000  22247600

 [285 rows x 4 columns],
 Price       Date   CD_ACAO      Close    Volume
 0     2025-01-02  AXIA3.SA  31.018433  10854400
 1     2025-01-03  AXIA3.SA  30.607893  14388900
 2     2025-01-06  AXIA3.SA  31.000187   8139400
 3     2025-01-07  AXIA3.SA  31.173519   4703200
 4     2025-01-08  AXIA3.SA  31.118786  10582100
 ..           ...       ...        ...       ...
 280   2026-02-13  AXIA3.SA  58.430000   6783100
 281   2026-02-18  AXIA3.SA  58.580002   7373000
 282   2026-02-19  AXIA3.SA  61.180000  13968500
 283   2026-02-20  AXIA3.SA  61.200001  16408300
 284   2026-02-23  AXIA3.SA  60.529999   6964000

 [285 rows x 4 columns]]

In [13]:
talib.BBANDS(df['Close'])

(0            NaN
 1            NaN
 2            NaN
 3            NaN
 4      31.380741
          ...
 280    59.625988
 281    59.629622
 282    61.333370
 283    62.178558
 284    62.448681
 Length: 285, dtype: float64,
 0            NaN
 1            NaN
 2            NaN
 3            NaN
 4      30.983764
          ...
 280    58.870000
 281    58.860000
 282    59.326000
 283    59.656001
 284    59.984000
 Length: 285, dtype: float64,
 0            NaN
 1            NaN
 2            NaN
 3            NaN
 4      30.586786
          ...
 280    58.114011
 281    58.090378
 282    57.318630
 283    57.133443
 284    57.519319
 Length: 285, dtype: float64)

In [ ]:
for df in ne:
    df['RSI'] = talib.RSI(df['Close'].values, timeperiod=14)
    macd, signal, hist = talib.MACD(df['Close'].values)
    df['MACD'] = macd
    df['MACD_Signal'] = signal
    df['MACD_Hist'] = hist
    ##df['OBV'] = talib.OBV(df['Close'],df['Volume']) 
    
    

ne[1]

Price,Date,CD_ACAO,Close,Volume,RSI,MACD,MACD_Signal,MACD_Hist,OBV
0,2025-01-02,ASAI3.SA,5.281979,15340600,NaN,NaN,NaN,NaN,15340600.0
1,2025-01-03,ASAI3.SA,5.252904,13594200,NaN,NaN,NaN,NaN,1746400.0
2,2025-01-06,ASAI3.SA,5.514580,13729000,NaN,NaN,NaN,NaN,15475400.0
3,2025-01-07,ASAI3.SA,5.714286,22063000,NaN,NaN,NaN,NaN,37538400.0
4,2025-01-08,ASAI3.SA,5.556650,27185400,NaN,NaN,NaN,NaN,10353000.0
...,...,...,...,...,...,...,...,...,...
280,2026-02-13,ASAI3.SA,9.900000,24336600,76.513529,0.438215,0.311423,0.126791,11813100.0
281,2026-02-18,ASAI3.SA,9.640000,15515700,69.417897,0.456232,0.340385,0.115847,-3702600.0
282,2026-02-19,ASAI3.SA,9.460000,13227400,64.928636,0.450790,0.362466,0.088324,-16930000.0
283,2026-02-20,ASAI3.SA,9.500000,14268100,65.463147,0.444580,0.378889,0.065691,-2661900.0
284,2026-02-23,ASAI3.SA,9.270000,22247600,59.817843,0.416301,0.386371,0.029929,-24909500.0